openapi: 3.0.3
info:
  title: Api Rest centre régional de maintenance de kébili
  contact:
    name: Benhamad Mhemed & Khaled Mokhtar
    email: mhemed.benhamad@gmail.com
  version: 1.0.1

servers:
  - url: http://localhost:3000
    description: routes backend


# les routes 
paths:

#login /////  
  /login/user/data:
    get:
      tags:
        - authentification
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserData"
  /login/user/add:
    post:
      tags:
        - authentification
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/UserAdd"
      responses:
        '200':
          description: ajouté avec sucée
          
  /login/user/delete/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
        - authentification
      responses:
        '200':
           description: supprimé avec succée
              
  /login/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - authentification
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/UserAdd"
      responses:
        '200':
           description: modifié avec succée
       

#membre /////
  /membre_equipe/membre_equipe_et_login:
    get:
      tags:
        - membres Equipe
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/membreData"
  /membre_equipe/add:
    post:
      tags:
        - membres Equipe
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/membreAdd"
      responses:
        '200':
          description: ajouté avec sucée
          
  /membre_equipe/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
        - membres Equipe
      responses:
        '200':
           description: supprimé avec succée
              
  /membre_equipe/update/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - membres Equipe
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/membreAdd"
      responses:
        '200':
           description: modifié avec succée
       
  /membre_equipe/membre_equipe_login/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - membres Equipe
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/membreData"    

  /project:
    get:
      tags:
        - projets
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/projectData"

    post:
      tags:
        - projets
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/projectAdd"
      responses:
        '200':
          description: ajouté avec sucée
    
  /project/{id}:      
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - projets
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/projectAdd"
      responses:
        '200':
           description: modifié avec succée
           
    get:
      tags:
        - projets
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/projectData"  
    delete:
      tags:
        - projets
      responses:
        '200':
           description: supprimé avec succée
           
  /infrastructures:
    get:
      tags:
        - infrastructures
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/infraData"

    post:
      tags:
        - infrastructures
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/infraAdd"
      responses:
        '200':
          description: ajouté avec sucée
    
  /infrastructures/{id}:      
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - infrastructures
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/infraAdd"
      responses:
        '200':
           description: modifié avec succée
           
    get:
      tags:
        - infrastructures
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/infraData"  
    delete:
      tags:
        - infrastructures
      responses:
        '200':
           description: supprimé avec succée
         
         
  /batiment_admin:
    get:
      tags:
        - batiments administratives
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/bat"

    post:
      tags:
        - batiments administratives
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/bat"
      responses:
        '200':
          description: ajouté avec sucée
    
  /batiment_admin/{id}:      
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - batiments administratives
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/modifbat"
      responses:
        '200':
           description: modifié avec succée
           
    delete:
      tags:
        - batiments administratives
      responses:
        '200':
           description: supprimé avec succée
  
  /suivi:
    get:
      tags:
        - suivis
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/suiviData"

    post:
      tags:
        - suivis
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/suiviAdd"
      responses:
        '200':
          description: ajouté avec sucée
    
  /suivi/{id}:      
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - suivis
      requestBody:
        required: true
        content:
            "application/x-www-form-urlencoded":
              schema:
                  $ref: "#/components/schemas/suiviAdd"
      responses:
        '200':
           description: modifié avec succée
           
    get:
      tags:
        - suivis
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/suiviData"  
    delete:
      tags:
        - suivis
      responses:
        '200':
           description: supprimé avec succée
                             
components:
  schemas:
    
    UserData:
      type: object
      properties:
        id_log:
          type: integer
        username:
          type: string
        password:
          type: string
        role:
          type: string
          
    UserAdd:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string


    membreData:
      type: object
      properties:
        Id_Mem_Eq:
          type: integer
        Nom_Mem_Eq:
          type: string
        Pren_Mem_Eq:
          type: string
        Adr_Mem_Eq: 
          type: string
        Email_Mem_Eq: 
          type: string
        Tel_Mem_Eq: 
          type: string
        Poste_Mem_eq: 
          type: string
        login_id_log:
          type: integer
        username: 
          type: string
        password: 
          type: string
        role: 
          type: string
          
    membreAdd:
      type: object
      properties:
        Nom_Mem_Eq:
          type: string
        Pren_Mem_Eq:
          type: string
        Adr_Mem_Eq: 
          type: string
        Email_Mem_Eq: 
          type: string
        Tel_Mem_Eq: 
          type: string
        Poste_Mem_eq: 
          type: string
        login_id_log:
          type: integer
          
    projectData:
      type: object
      properties:
        Id_Proj:
           type: integer
        Nom_Proj: 
           type: string
        Desc_Proj:
           type: string
        Objectifs:
           type: string
        Date_Deb_Proj: 
           type: string
           format: date
        Date_Fin_Proj: 
           type: string
           format: date
        Budget_Proj: 
           type: number
        Statut_Proj: 
           type: string
        Id_Infra_Str: 
           type: integer
           
    projectAdd:
      type: object
      properties:
        Nom_Proj: 
           type: string
        Desc_Proj:
           type: string
        Objectifs:
           type: string
        Date_Deb_Proj: 
           type: string
           format: date
        Date_Fin_Proj: 
           type: string
           format: date
        Budget_Proj: 
           type: number
        Statut_Proj: 
           type: string
        Id_Infra_Str: 
           type: integer
           
    infraData:
      type: object
      properties:    
        Id_Infra_Str: 
          type: integer
        Nom_Infra_Str:
          type: string
        Adr_Infra_Str:
          type: string
        Directeur_Infra_Str: 
          type: string
          
    infraAdd:
      type: object
      properties:    
        Nom_Infra_Str:
          type: string
        Adr_Infra_Str:
          type: string
        Directeur_Infra_Str: 
          type: string
      
    bat:
      type: object
      properties:     
        Id_Infra_Str: 
          type: integer
        Surface_Bat:
          type: number
        Nb_Etages: 
          type: integer
        Usages: 
          type: string
    modifbat:
      type: object
      properties:     
        Surface_Bat:
          type: number
        Nb_Etages: 
          type: integer
        Usages: 
          type: string
    suiviData:
      type: object
      properties:
        Id_Suiv:
          type: integer
        Obj_Suiv: 
          type: string
        Desc_Suiv:
          type: string
        Date_Deb_Suiv:
          type: string
        Date_Fin_Suiv: 
          type: string
        Statut_Suiv: 
          type: string
        Remarques_Suiv:
          type: string
        Id_Proj:
          type: integer
    suiviAdd:
      type: object
      properties:
        Obj_Suiv: 
          type: string
        Desc_Suiv:
          type: string
        Date_Deb_Suiv:
          type: string
        Date_Fin_Suiv: 
          type: string
        Statut_Suiv: 
          type: string
        Remarques_Suiv:
          type: string
        Id_Proj:
          type: integer
tags:
  - name: authentification
    description: Liste des utilisateurs
  - name: membres Equipe
    description: Liste des membres d'équipe
  - name: projets
    description: Liste des projets
  - name: infrastructures
    description: Liste des infrastures
  - name: batiments administratives
    description: Liste des bâtiments administratives
  - name: suivis
    description: Suivi des projets